### ISSUE TITLE
Installation completes but application fails to start

### ISSUE THREAD

**Issue by WestNab** [powertab/powertabeditor#222]
Installing the 32 bit Windows 2.0.0 alpha 9 on Windows Vista seemed to work, but starting gave message: "This application failed to start because api-ms-win-crt-runtime-l1-1-0.dll was not found. Re-installing the application may fix this problem". But it didn't.

**Comment by DontBelieveMe** [comment]
This is because it cannot find the Microsoft Redistributable for visual studio 2015 is missing.
Try updating all updates using Windows Update and then install the Redistributable for vs 2015 (found here (http://download.microsoft.com/download/9/b/3/9b3d2920-49f7-4e76-a55c-d72b51e44537/vc_redist.x86.exe))

**Comment by cameronwhite** [comment]
I think this can be closed unless there are further replies / issues
