### ISSUE TITLE
Loosing heads from guitar to bass

### ISSUE THREAD

**Issue by sbonaime** [powertab/powertabeditor#492]
With default settings I can write some notes 

<img width="351" alt="Capture d’écran 2024-11-12 à 08 43 46" src="https://github.com/user-attachments/assets/bc0659c5-35fe-43f3-a0a5-bd582d505652">

When I change the number of strings to 4 (bass), I loose the heads on the notes

<img width="715" alt="Capture d’écran 2024-11-12 à 08 43 54" src="https://github.com/user-attachments/assets/bbdaaa74-53af-40ac-9eab-55c36e37655a">

<img width="368" alt="Capture d’écran 2024-11-12 à 08 43 59" src="https://github.com/user-attachments/assets/2589f46a-230c-4a86-8bc5-5c0ddab0d242">

Any idea ? 

thanks

**Comment by cameronwhite** [comment]
In the final screenshot you can see that `Player 1` switched to `(No Players)`, so there is no player (and tuning) assigned to the staff since the number of strings no longer matches.
I think you probably want to change the player's tuning to the appropriate 4-string tuning and then re-assign it to the staff
