### ISSUE TITLE
Linux version (flatpak & snap) can not save files

### ISSUE THREAD

**Issue by konsumschaf** [powertab/powertabeditor#498]
**Description**
The Linux Version is not able to save a file

**To Reproduce**
Open Powertab, File -> New, File -> Save, enter some name, get error message: 

Error saving file: filesystem error: cannot rename: Ungültiger Link über Gerätegrenzen hinweg [/tmp/test.pt2.new] [/run/user/1000/doc/cef48855/test.pt2]

**Additional Info**
Tried to alter the permissions within flatpak (changed file permissions to HOST) - did not change the behaviour

**Version**
Power Tab Editor 2.0.20 (v2.0.20-0-geff05f0)
Kubuntu 22.04 and Kubuntu 22.10

**Comment by cameronwhite** [comment]
Thanks for the report! I'll try to get a fix out for this ASAP
It looks like it might be caused by the temp folder appearing as a different filesystem volume when under flatpak, rather than a permission issue

- The `filesystem::rename()` added in 62298b1 likely needs to fall back to doing a copy + remove if it fails
- Rather than using the temp folder, under snap/flatpak it's also probably safer to use the application's user data folder which we're also using now for auto-backups (7280ee78807588490902eadb3311e08d206cef3c)

**Comment by konsumschaf** [comment]
Thanks a lot! I would like to test this, but the actions only offer Win & Mac build. Where can I get the Linux Builds?

**Comment by konsumschaf** [comment]
OK, thanks, I can confirm that saving is working now!

**Comment by cameronwhite** [comment]
Great, thanks for testing!
